version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: |
                git config --global user.email $GH_EMAIL
                git config --global user.name $GH_NAME
                npm run deploy
workflows:
    build-test-deploy:
      jobs:
        - build-test-deploy:
            filters:
              branches:
                ignore: gh-pages
